// Generated by CoffeeScript 1.9.1
var crawlUrls, crawler, processUrl, queue, seedUrl, totalNumProcessed, urlChecker;

queue = require('./lib/queue-controller');

urlChecker = require('./lib/url-controller');

crawler = require('./lib/crawler-controller');

totalNumProcessed = 0;

processUrl = function(url, parentUrl) {
  var x;
  queue.createJob({
    title: url,
    url: url,
    parent: parentUrl,
    datetime: Date.now()
  });
  return x = 1;
};

crawlUrls = function() {
  return queue.currentJob.on('new-job', function(job, jobId, done) {
    console.log("job: " + job + ", jobId: " + jobId);
    return urlChecker.crawlUrl(job.url).then(function(allowed) {
      console.log("end " + job.url);
      if (allowed) {
        return crawler.crawl(new crawler.Url(job.url), function(err, urls) {
          var i, len, url;
          if (err) {
            err.url = job.url;
            return console.log(err);
          }
          if (totalNumProcessed === 10000) {
            return process.exit();
          }
          if (totalNumProcessed % 100 === 0) {
            console.log("processed: " + totalNumProcessed);
          }
          totalNumProcessed++;
          for (i = 0, len = urls.length; i < len; i++) {
            url = urls[i];
            processUrl(url, job.url);
          }
          return done();
        });
      } else {
        return done();
      }
    });
  });
};

seedUrl = 'https://news.google.com/news/directory';

crawlUrls();

queue.createJob({
  title: seedUrl,
  url: seedUrl,
  datetime: Date.now()
});

queue.initialize();

process.once('SIGINT', function() {
  return console.log(processUrl);
}, 5000);
